# Generated by Django 5.2 on 2025-04-14 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usertoken_is_valid_usertoken_token_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='nick_name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(code='invalid_nickname', message='昵称只能包含字母、数字、下划线和中文', regex='^[a-zA-Z0-9_\\u4e00-\\u9fa5]+$')]),
        ),
    ]
