# Generated by Django 5.2 on 2025-04-15 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_users', models.IntegerField(default=10, verbose_name='最大用户数')),
                ('max_admins', models.IntegerField(default=2, verbose_name='最大管理员数')),
                ('max_storage_mb', models.IntegerField(default=1024, verbose_name='最大存储空间(MB)')),
                ('max_products', models.IntegerField(default=100, verbose_name='最大产品数')),
                ('current_storage_used_mb', models.IntegerField(default=0, verbose_name='当前已用存储空间(MB)')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to='common.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '租户配额',
                'verbose_name_plural': '租户配额',
                'db_table': 'tenant_quotas',
            },
        ),
    ]
