# Generated by Django 5.2 on 2025-04-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('product_count', models.IntegerField(default=0)),
                ('variation_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '导出历史',
                'verbose_name_plural': '导出历史',
                'db_table': 'export_history',
            },
        ),
        migrations.CreateModel(
            name='ExportList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '导出清单',
                'verbose_name_plural': '导出清单',
                'db_table': 'export_lists',
            },
        ),
        migrations.CreateModel(
            name='ExportListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '导出清单项',
                'verbose_name_plural': '导出清单项',
                'db_table': 'export_list_items',
            },
        ),
        migrations.CreateModel(
            name='ExportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('format', models.CharField(choices=[('woocommerce', 'WooCommerce'), ('custom', '自定义')], default='woocommerce', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('fields', models.JSONField(default=dict, help_text='要导出的字段配置')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '导出模板',
                'verbose_name_plural': '导出模板',
                'db_table': 'export_templates',
            },
        ),
    ]
