# Generated by Django 5.2 on 2025-04-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['menu_order', '-created_at'], 'verbose_name': '产品', 'verbose_name_plural': '产品'},
        ),
        migrations.AddField(
            model_name='product',
            name='menu_order',
            field=models.IntegerField(default=0, help_text='WooCommerce产品排序字段，值越小排序越靠前'),
        ),
    ]
